# Generated by Django 5.2 on 2025-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
