# Generated by Django 5.2 on 2025-10-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_admin_comment_question_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'question_categories',
                'indexes': [models.Index(fields=['name'], name='qcat_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('us_group', models.TextField()),
                ('username', models.TextField()),
                ('administrator', models.BooleanField(default=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['chat_id'], name='users_chat_id_idx'), models.Index(fields=['username'], name='users_username_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id',), name='users_chat_id_key')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSubcategory',
            fields=[
                ('subcategory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='questions.questioncategory')),
            ],
            options={
                'db_table': 'question_subcategories',
                'indexes': [models.Index(fields=['category'], name='qsubcat_category_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaticQuestion',
            fields=[
                ('static_question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='static_questions', to='questions.questioncategory')),
            ],
            options={
                'db_table': 'static_questions',
                'indexes': [models.Index(fields=['category'], name='squest_category_idx'), models.Index(fields=['name'], name='squest_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('dynamic_question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('answer', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_questions', to='questions.questioncategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_questions', to='questions.user')),
            ],
            options={
                'db_table': 'dynamic_questions',
                'indexes': [models.Index(fields=['category'], name='dquest_category_idx'), models.Index(fields=['user'], name='dquest_user_idx'), models.Index(fields=['answer'], name='dquest_answer_idx')],
            },
        ),
    ]
